manifest:
  projects:
    - name: mender-mcu
      url: https://github.com/mendersoftware/mender-mcu
      revision: main
      path: modules/mender-mcu
      import: true
    - name: ws2812-pwm
      url: https://github.com/haymanmk/ws2812-pwm.git
      revision: 5186892508e424ddec8d3359c0e99aadf89a0a91
      path: modules/ws2812-pwm
      import: true