#ifndef __CPU_MAP_H
#define __CPU_MAP_H

// Digital inputs

#define DIGITAL_INPUT_1_PIN  GPIO_PIN_0
#define DIGITAL_INPUT_1_PORT GPIOE
#define DIGITAL_INPUT_2_PIN  GPIO_PIN_2
#define DIGITAL_INPUT_2_PORT GPIOE
#define DIGITAL_INPUT_3_PIN  GPIO_PIN_3
#define DIGITAL_INPUT_3_PORT GPIOE
#define DIGITAL_INPUT_4_PIN  GPIO_PIN_4
#define DIGITAL_INPUT_4_PORT GPIOE
#define DIGITAL_INPUT_5_PIN  GPIO_PIN_5
#define DIGITAL_INPUT_5_PORT GPIOE
#define DIGITAL_INPUT_6_PIN  GPIO_PIN_6
#define DIGITAL_INPUT_6_PORT GPIOE
#define DIGITAL_INPUT_7_PIN  GPIO_PIN_7
#define DIGITAL_INPUT_7_PORT GPIOE
#define DIGITAL_INPUT_8_PIN  GPIO_PIN_8
#define DIGITAL_INPUT_8_PORT GPIOE
#define DIGITAL_INPUT_9_PIN  GPIO_PIN_10
#define DIGITAL_INPUT_9_PORT GPIOE
#define DIGITAL_INPUT_10_PIN  GPIO_PIN_0
#define DIGITAL_INPUT_10_PORT GPIOF
#define DIGITAL_INPUT_11_PIN  GPIO_PIN_1
#define DIGITAL_INPUT_11_PORT GPIOF
#define DIGITAL_INPUT_12_PIN  GPIO_PIN_2
#define DIGITAL_INPUT_12_PORT GPIOF
#define DIGITAL_INPUT_13_PIN  GPIO_PIN_4
#define DIGITAL_INPUT_13_PORT GPIOF
#define DIGITAL_INPUT_14_PIN  GPIO_PIN_7
#define DIGITAL_INPUT_14_PORT GPIOF
#define DIGITAL_INPUT_15_PIN  GPIO_PIN_8
#define DIGITAL_INPUT_15_PORT GPIOF
#define DIGITAL_INPUT_16_PIN  GPIO_PIN_9
#define DIGITAL_INPUT_16_PORT GPIOF


// Digital outputs
enum {
    DIGITAL_OUTPUT_1 = 1,
    DIGITAL_OUTPUT_2,
    DIGITAL_OUTPUT_3,
    DIGITAL_OUTPUT_4,
    DIGITAL_OUTPUT_5,
    DIGITAL_OUTPUT_6,
    DIGITAL_OUTPUT_7,
    DIGITAL_OUTPUT_8,
    DIGITAL_OUTPUT_9,
    DIGITAL_OUTPUT_10,
    DIGITAL_OUTPUT_11,
    DIGITAL_OUTPUT_12,
    DIGITAL_OUTPUT_13,
    DIGITAL_OUTPUT_14,
    DIGITAL_OUTPUT_15,
    DIGITAL_OUTPUT_16,
#ifdef DIGITAL_OUTPUT_17_PIN
    DIGITAL_OUTPUT_17,
#endif
#ifdef DIGITAL_OUTPUT_18_PIN
    DIGITAL_OUTPUT_18,
#endif
    DIGITAL_OUTPUT_MAX,
};

#define DIGITAL_OUTPUT_1_PIN  GPIO_PIN_7
#define DIGITAL_OUTPUT_1_PORT GPIOC
#define DIGITAL_OUTPUT_2_PIN  GPIO_PIN_8
#define DIGITAL_OUTPUT_2_PORT GPIOC
#define DIGITAL_OUTPUT_3_PIN  GPIO_PIN_9
#define DIGITAL_OUTPUT_3_PORT GPIOC
#define DIGITAL_OUTPUT_4_PIN  GPIO_PIN_10
#define DIGITAL_OUTPUT_4_PORT GPIOC
#define DIGITAL_OUTPUT_5_PIN  GPIO_PIN_11
#define DIGITAL_OUTPUT_5_PORT GPIOC
#define DIGITAL_OUTPUT_6_PIN  GPIO_PIN_12
#define DIGITAL_OUTPUT_6_PORT GPIOC
#define DIGITAL_OUTPUT_7_PIN  GPIO_PIN_0
#define DIGITAL_OUTPUT_7_PORT GPIOD
#define DIGITAL_OUTPUT_8_PIN  GPIO_PIN_1
#define DIGITAL_OUTPUT_8_PORT GPIOD
#define DIGITAL_OUTPUT_9_PIN  GPIO_PIN_2
#define DIGITAL_OUTPUT_9_PORT GPIOD
#define DIGITAL_OUTPUT_10_PIN  GPIO_PIN_3
#define DIGITAL_OUTPUT_10_PORT GPIOD
#define DIGITAL_OUTPUT_11_PIN  GPIO_PIN_4
#define DIGITAL_OUTPUT_11_PORT GPIOD
#define DIGITAL_OUTPUT_12_PIN  GPIO_PIN_6
#define DIGITAL_OUTPUT_12_PORT GPIOD
#define DIGITAL_OUTPUT_13_PIN  GPIO_PIN_7
#define DIGITAL_OUTPUT_13_PORT GPIOD
#define DIGITAL_OUTPUT_14_PIN  GPIO_PIN_11
#define DIGITAL_OUTPUT_14_PORT GPIOD
#define DIGITAL_OUTPUT_15_PIN  GPIO_PIN_12
#define DIGITAL_OUTPUT_15_PORT GPIOD
#define DIGITAL_OUTPUT_16_PIN  GPIO_PIN_13
#define DIGITAL_OUTPUT_16_PORT GPIOD

// PWM WS28XX LED
enum {
    PWM_WS28XX_LED_1 = 1,
    PWM_WS28XX_LED_MAX,
};

#endif